$color = rgba(7, 7, 7, 1)
$inner_color = rgba(7, 7, 7, 0.66)
$outer_color = rgba(236, 139, 157, 1)
$font_color = rgba(180, 179, 179, 1)
$placeholder_color = rgba(180, 179, 179, 0.7)
$check_color = rgba(255, 199, 110, 1)
