# Background and foreground colors
background = #0b011b
foreground = #ffb6ff

# Standard colors
palette = 0=#0b011b
palette = 1=#aa81b7
palette = 2=#8ec3ff
palette = 3=#ffccff
palette = 4=#7974b6
palette = 5=#b796e8
palette = 6=#b0d3ff
palette = 7=#ffb6ff

# Bright colors
palette = 8=#5e5c62
palette = 9=#c592d5
palette = 10=#94daff
palette = 11=#ffc6ff
palette = 12=#8d86d8
palette = 13=#d1a6ff
palette = 14=#bee8ff
palette = 15=#f5f3ff
