$color = rgba(11, 1, 27, 1)
$inner_color = rgba(11, 1, 27, 0.66)
$outer_color = rgba(183, 150, 232, 1)
$font_color = rgba(255, 182, 255, 1)
$placeholder_color = rgba(255, 182, 255, 0.7)
$check_color = rgba(176, 211, 255, 1)
