background            #0b011b
foreground            #ffb6ff

# black
color0  #0b011b
color8  #5e5c62

# red
color1  #aa81b7
color9  #c592d5

# green
color2  #8ec3ff
color10 #94daff

# yellow
color3  #ffccff
color11 #ffc6ff

# blue
color4  #7974b6
color12 #8d86d8

# magenta
color5  #b796e8
color13 #d1a6ff

#cyan
color6  #b0d3ff
color14 #bee8ff

#white
color7  #ffb6ff
color15 #f5f3ff


