accent = "#6797ff"
cursor = "#9BF5F8"
foreground = "#9BF5F8"
background = "#020003"
selection_foreground = "#020003"
selection_background = "#9BF5F8"
color0 = "#020003"
color1 = "#d44109"
color2 = "#ffac74"
color3 = "#ec773e"
color4 = "#6797ff"
color5 = "#d400e6"
color6 = "#86b9ff"
color7 = "#9BF5F8"
color8 = "#69656a"
color9 = "#ff6222"
color10 = "#ffb152"
color11 = "#ff994e"
color12 = "#89b9ff"
color13 = "#fd4aff"
color14 = "#9dd3ff"
color15 = "#71ffff"
border = "#1a1a1f"
comment = "#6c7086"
