$color = rgba(2, 0, 3, 1)
$inner_color = rgba(2, 0, 3, 0.66)
$outer_color = rgba(212, 0, 230, 1)
$font_color = rgba(155, 245, 248, 1)
$placeholder_color = rgba(155, 245, 248, 0.7)
$check_color = rgba(134, 185, 255, 1)
