background            #020003
foreground            #9BF5F8

# black
color0  #020003
color8  #69656a

# red
color1  #d44109
color9  #ff6222

# green
color2  #ffac74
color10 #ffb152

# yellow
color3  #ec773e
color11 #ff994e

# blue
color4  #6797ff
color12 #89b9ff

# magenta
color5  #d400e6
color13 #fd4aff

#cyan
color6  #86b9ff
color14 #9dd3ff

#white
color7  #9BF5F8
color15 #71ffff


