accent = "#7974b6"
cursor = "#ffb6ff"
foreground = "#ffb6ff"
background = "#0b011b"
selection_foreground = "#0b011b"
selection_background = "#ffb6ff"
color0 = "#0b011b"
color1 = "#aa81b7"
color2 = "#8ec3ff"
color3 = "#ffccff"
color4 = "#7974b6"
color5 = "#b796e8"
color6 = "#b0d3ff"
color7 = "#ffb6ff"
color8 = "#5e5c62"
color9 = "#c592d5"
color10 = "#94daff"
color11 = "#ffc6ff"
color12 = "#8d86d8"
color13 = "#d1a6ff"
color14 = "#bee8ff"
color15 = "#f5f3ff"
border = "#1a1a1f"
comment = "#6c7086"
