accent = "#7f7c9b"
cursor = "#D2A7B4"
foreground = "#D2A7B4"
background = "#06080C"
border = "#15171b"
selection_foreground = "#06080C"
selection_background = "#D2A7B4"
color0 = "#06080C"
color1 = "#a28ea6"
color2 = "#aec5e5"
color3 = "#ffe2fe"
color4 = "#7f7c9b"
color5 = "#b4a4ca"
color6 = "#cad9ff"
color7 = "#D2A7B4"
color8 = "#5c5f64"
color9 = "#bba1c0"
color10 = "#bedcff"
color11 = "#ffdeff"
color12 = "#9490b7"
color13 = "#ccb7e8"
color14 = "#ddefff"
color15 = "#f6f3fe"
comment = "#5c5f64"
