# Background and foreground colors
background = #06080C
foreground = #D2A7B4

# Standard colors
palette = 0=#06080C
palette = 1=#a28ea6
palette = 2=#aec5e5
palette = 3=#ffe2fe
palette = 4=#7f7c9b
palette = 5=#b4a4ca
palette = 6=#cad9ff
palette = 7=#D2A7B4

# Bright colors
palette = 8=#5c5f64
palette = 9=#bba1c0
palette = 10=#bedcff
palette = 11=#ffdeff
palette = 12=#9490b7
palette = 13=#ccb7e8
palette = 14=#ddefff
palette = 15=#f6f3fe
