accent = "#af6376"
cursor = "#FADAA3"
foreground = "#FADAA3"
background = "#140202"
selection_foreground = "#140202"
selection_background = "#FADAA3"
color0 = "#140202"
color1 = "#c37f6c"
color2 = "#f2b072"
color3 = "#ffd896"
color4 = "#af6376"
color5 = "#eb898a"
color6 = "#ffcb62"
color7 = "#FADAA3"
color8 = "#635c5b"
color9 = "#e48f78"
color10 = "#ffc16d"
color11 = "#ffd480"
color12 = "#ce7189"
color13 = "#ff9497"
color14 = "#ffde54"
color15 = "#fff2ee"
border = "#1a1a1f"
comment = "#6c7086"
