# Background and foreground colors
background = #140202
foreground = #FADAA3

# Standard colors
palette = 0=#140202
palette = 1=#c37f6c
palette = 2=#f2b072
palette = 3=#ffd896
palette = 4=#af6376
palette = 5=#eb898a
palette = 6=#ffcb62
palette = 7=#FADAA3

# Bright colors
palette = 8=#635c5b
palette = 9=#e48f78
palette = 10=#ffc16d
palette = 11=#ffd480
palette = 12=#ce7189
palette = 13=#ff9497
palette = 14=#ffde54
palette = 15=#fff2ee
