$color = rgba(20, 2, 2, 1)
$inner_color = rgba(20, 2, 2, 0.66)
$outer_color = rgba(235, 137, 138, 1)
$font_color = rgba(250, 218, 163, 1)
$placeholder_color = rgba(250, 218, 163, 0.7)
$check_color = rgba(255, 203, 98, 1)
