background            #140202
foreground            #FADAA3

# black
color0  #140202
color8  #635c5b

# red
color1  #c37f6c
color9  #e48f78

# green
color2  #f2b072
color10 #ffc16d

# yellow
color3  #ffd896
color11 #ffd480

# blue
color4  #af6376
color12 #ce7189

# magenta
color5  #eb898a
color13 #ff9497

#cyan
color6  #ffcb62
color14 #ffde54

#white
color7  #FADAA3
color15 #fff2ee


