accent = "#667dcb"
cursor = "#DEF1F4"
foreground = "#DEF1F4"
background = "#11100C"
border = "#201f1b"
selection_foreground = "#11100C"
selection_background = "#DEF1F4"
color0 = "#11100C"
color1 = "#b46f38"
color2 = "#b27731"
color3 = "#c69647"
color4 = "#667dcb"
color5 = "#6f76c6"
color6 = "#60bdee"
color7 = "#DEF1F4"
color8 = "#6b6a63"
color9 = "#e09249"
color10 = "#dd9b3c"
color11 = "#f1bc50"
color12 = "#889eff"
color13 = "#9397fd"
color14 = "#77dcff"
color15 = "#bdf7ff"
comment = "#6b6a63"
