# Background and foreground colors
background = #11100C
foreground = #DEF1F4

# Standard colors
palette = 0=#11100C
palette = 1=#b46f38
palette = 2=#b27731
palette = 3=#c69647
palette = 4=#667dcb
palette = 5=#6f76c6
palette = 6=#60bdee
palette = 7=#DEF1F4

# Bright colors
palette = 8=#6b6a63
palette = 9=#e09249
palette = 10=#dd9b3c
palette = 11=#f1bc50
palette = 12=#889eff
palette = 13=#9397fd
palette = 14=#77dcff
palette = 15=#bdf7ff
