$color = rgba(0, 0, 0, 1)
$inner_color = rgba(0, 0, 0, 0.66)
$outer_color = rgba(169, 169, 169, 1)
$font_color = rgba(244, 244, 244, 1)
$placeholder_color = rgba(244, 244, 244, 0.7)
$check_color = rgba(215, 215, 215, 1)
