accent = "#8071b3"
cursor = "#E1E5FC"
foreground = "#E1E5FC"
background = "#010025"
selection_foreground = "#010025"
selection_background = "#E1E5FC"
color0 = "#010025"
color1 = "#af80b1"
color2 = "#97c0ff"
color3 = "#ffcbff"
color4 = "#8071b3"
color5 = "#bf93e2"
color6 = "#bdcfff"
color7 = "#E1E5FC"
color8 = "#595b61"
color9 = "#cc90cf"
color10 = "#a1d6ff"
color11 = "#ffc4ff"
color12 = "#9683d4"
color13 = "#dba3ff"
color14 = "#cee3ff"
color15 = "#f7f3fe"
border = "#1a1a1f"
comment = "#6c7086"
