# Background and foreground colors
background = #010025
foreground = #E1E5FC

# Standard colors
palette = 0=#010025
palette = 1=#af80b1
palette = 2=#97c0ff
palette = 3=#ffcbff
palette = 4=#8071b3
palette = 5=#bf93e2
palette = 6=#bdcfff
palette = 7=#E1E5FC

# Bright colors
palette = 8=#595b61
palette = 9=#cc90cf
palette = 10=#a1d6ff
palette = 11=#ffc4ff
palette = 12=#9683d4
palette = 13=#dba3ff
palette = 14=#cee3ff
palette = 15=#f7f3fe
