$color = rgba(1, 0, 37, 1)
$inner_color = rgba(1, 0, 37, 0.66)
$outer_color = rgba(191, 147, 226, 1)
$font_color = rgba(225, 229, 252, 1)
$placeholder_color = rgba(225, 229, 252, 0.7)
$check_color = rgba(189, 207, 255, 1)
