background            #010025
foreground            #E1E5FC

# black
color0  #010025
color8  #595b61

# red
color1  #af80b1
color9  #cc90cf

# green
color2  #97c0ff
color10 #a1d6ff

# yellow
color3  #ffcbff
color11 #ffc4ff

# blue
color4  #8071b3
color12 #9683d4

# magenta
color5  #bf93e2
color13 #dba3ff

#cyan
color6  #bdcfff
color14 #cee3ff

#white
color7  #E1E5FC
color15 #f7f3fe


