accent = "#5979c3"
cursor = "#D2E3E9"
foreground = "#D2E3E9"
background = "#0c0113"
selection_foreground = "#0c0113"
selection_background = "#D2E3E9"
color0 = "#0c0113"
color1 = "#c05f3c"
color2 = "#7cc481"
color3 = "#8e861d"
color4 = "#5979c3"
color5 = "#af59bf"
color6 = "#7de0a2"
color7 = "#D2E3E9"
color8 = "#6b676d"
color9 = "#ef8052"
color10 = "#93e88e"
color11 = "#b3ad05"
color12 = "#7a9bf9"
color13 = "#dc75f6"
color14 = "#65f596"
color15 = "#c0f5ff"
border = "#1a1a1f"
comment = "#6c7086"
