# Background and foreground colors
background = #0c0113
foreground = #D2E3E9

# Standard colors
palette = 0=#0c0113
palette = 1=#c05f3c
palette = 2=#7cc481
palette = 3=#8e861d
palette = 4=#5979c3
palette = 5=#af59bf
palette = 6=#7de0a2
palette = 7=#D2E3E9

# Bright colors
palette = 8=#6b676d
palette = 9=#ef8052
palette = 10=#93e88e
palette = 11=#b3ad05
palette = 12=#7a9bf9
palette = 13=#dc75f6
palette = 14=#65f596
palette = 15=#c0f5ff
