$color = rgba(12, 1, 19, 1)
$inner_color = rgba(12, 1, 19, 0.66)
$outer_color = rgba(175, 89, 191, 1)
$font_color = rgba(210, 227, 233, 1)
$placeholder_color = rgba(210, 227, 233, 0.7)
$check_color = rgba(125, 224, 162, 1)
