background            #0c0113
foreground            #D2E3E9

# black
color0  #0c0113
color8  #6b676d

# red
color1  #c05f3c
color9  #ef8052

# green
color2  #7cc481
color10 #93e88e

# yellow
color3  #8e861d
color11 #b3ad05

# blue
color4  #5979c3
color12 #7a9bf9

# magenta
color5  #af59bf
color13 #dc75f6

#cyan
color6  #7de0a2
color14 #65f596

#white
color7  #D2E3E9
color15 #c0f5ff


