background            #060709
foreground            #DCD6C4

# black
color0  #060709
color8  #5a5d63

# red
color1  #a39070
color9  #bda57c

# green
color2  #c3c395
color10 #dadb9e

# yellow
color3  #f9f1b8
color11 #fef4ae

# blue
color4  #6b8666
color12 #7c9d76

# magenta
color5  #c7a07d
color13 #e6b486

#cyan
color6  #cde0a6
color14 #e2f9b1

#white
color7  #DCD6C4
color15 #f8f5ea


