accent = "#808080"
cursor = "#d7d7d7"
foreground = "#d7d7d7"
background = "#090909"
border = "#181818"
selection_foreground = "#090909"
selection_background = "#d7d7d7"
color0 = "#090909"
color1 = "#969696"
color2 = "#c3c3c3"
color3 = "#f2f2f2"
color4 = "#808080"
color5 = "#acacac"
color6 = "#dadada"
color7 = "#d7d7d7"
color8 = "#62605a"
color9 = "#a8a8a8"
color10 = "#d6d6d6"
color11 = "#f5f5f5"
color12 = "#929292"
color13 = "#bfbfbf"
color14 = "#eeeeee"
color15 = "#fcfcfc"
comment = "#62605a"
