$color = rgba(9, 9, 9, 1)
$inner_color = rgba(9, 9, 9, 0.66)
$outer_color = rgba(172, 172, 172, 1)
$font_color = rgba(215, 215, 215, 1)
$placeholder_color = rgba(215, 215, 215, 0.7)
$check_color = rgba(218, 218, 218, 1)
