accent = "#5f74e2"
cursor = "#FAD800"
foreground = "#FAD800"
background = "#030318"
selection_foreground = "#030318"
selection_background = "#FAD800"
color0 = "#030318"
color1 = "#d25548"
color2 = "#f7cb00"
color3 = "#bc9a00"
color4 = "#5f74e2"
color5 = "#af53b4"
color6 = "#6573ec"
color7 = "#FAD800"
color8 = "#67686e"
color9 = "#ff7563"
color10 = "#ffd700"
color11 = "#e5c100"
color12 = "#8293ff"
color13 = "#dd6ee9"
color14 = "#8891ff"
color15 = "#ffe500"
border = "#1a1a1f"
comment = "#6c7086"
