# Background and foreground colors
background = #030318
foreground = #FAD800

# Standard colors
palette = 0=#030318
palette = 1=#d25548
palette = 2=#f7cb00
palette = 3=#bc9a00
palette = 4=#5f74e2
palette = 5=#af53b4
palette = 6=#6573ec
palette = 7=#FAD800

# Bright colors
palette = 8=#67686e
palette = 9=#ff7563
palette = 10=#ffd700
palette = 11=#e5c100
palette = 12=#8293ff
palette = 13=#dd6ee9
palette = 14=#8891ff
palette = 15=#ffe500
