$color = rgba(3, 3, 24, 1)
$inner_color = rgba(3, 3, 24, 0.66)
$outer_color = rgba(175, 83, 180, 1)
$font_color = rgba(250, 216, 0, 1)
$placeholder_color = rgba(250, 216, 0, 0.7)
$check_color = rgba(101, 115, 236, 1)
