accent = "#6b8666"
cursor = "#DCD6C4"
foreground = "#DCD6C4"
background = "#060709"
border = "#151618"
selection_foreground = "#060709"
selection_background = "#DCD6C4"
color0 = "#060709"
color1 = "#a39070"
color2 = "#c3c395"
color3 = "#f9f1b8"
color4 = "#6b8666"
color5 = "#c7a07d"
color6 = "#cde0a6"
color7 = "#DCD6C4"
color8 = "#5a5d63"
color9 = "#bda57c"
color10 = "#dadb9e"
color11 = "#fef4ae"
color12 = "#7c9d76"
color13 = "#e6b486"
color14 = "#e2f9b1"
color15 = "#f8f5ea"
comment = "#5a5d63"
