# Background and foreground colors
background = #060709
foreground = #DCD6C4

# Standard colors
palette = 0=#060709
palette = 1=#a39070
palette = 2=#c3c395
palette = 3=#f9f1b8
palette = 4=#6b8666
palette = 5=#c7a07d
palette = 6=#cde0a6
palette = 7=#DCD6C4

# Bright colors
palette = 8=#5a5d63
palette = 9=#bda57c
palette = 10=#dadb9e
palette = 11=#fef4ae
palette = 12=#7c9d76
palette = 13=#e6b486
palette = 14=#e2f9b1
palette = 15=#f8f5ea
