background            #06080C
foreground            #D2A7B4

# black
color0  #06080C
color8  #5c5f64

# red
color1  #a28ea6
color9  #bba1c0

# green
color2  #aec5e5
color10 #bedcff

# yellow
color3  #ffe2fe
color11 #ffdeff

# blue
color4  #7f7c9b
color12 #9490b7

# magenta
color5  #b4a4ca
color13 #ccb7e8

#cyan
color6  #cad9ff
color14 #ddefff

#white
color7  #D2A7B4
color15 #f6f3fe


