[colors]
[colors.primary]
background = "#000000"
foreground = "#f4f4f4"

[colors.normal]
black   = "#000000"
red     = "#939393"
green   = "#bfbfbf"
yellow  = "#eeeeee"
blue    = "#7d7d7d"
magenta = "#a9a9a9"
cyan    = "#d7d7d7"
white   = "#f4f4f4"

[colors.bright]
black   = "#686163"
red     = "#a5a5a5"
green   = "#d3d3d3"
yellow  = "#f5f5f5"
blue    = "#8f8f8f"
magenta = "#bcbcbc"
cyan    = "#eaeaea"
white   = "#fcfcfc"

[colors.cursor]
text   = "#000000"
cursor = "#f4f4f4"
