# Background and foreground colors
background = #000000
foreground = #f4f4f4

# Standard colors
palette = 0=#000000
palette = 1=#939393
palette = 2=#bfbfbf
palette = 3=#eeeeee
palette = 4=#7d7d7d
palette = 5=#a9a9a9
palette = 6=#d7d7d7
palette = 7=#f4f4f4

# Bright colors
palette = 8=#686163
palette = 9=#a5a5a5
palette = 10=#d3d3d3
palette = 11=#f5f5f5
palette = 12=#8f8f8f
palette = 13=#bcbcbc
palette = 14=#eaeaea
palette = 15=#fcfcfc
