accent = "#447edf"
cursor = "#63E3B5"
foreground = "#63E3B5"
background = "#060217"
selection_foreground = "#060217"
selection_background = "#63E3B5"
color0 = "#060217"
color1 = "#d45146"
color2 = "#dd6b2f"
color3 = "#ff954b"
color4 = "#447edf"
color5 = "#aa57b2"
color6 = "#76b4ff"
color7 = "#63E3B5"
color8 = "#68686e"
color9 = "#ff7161"
color10 = "#ff8d3e"
color11 = "#ffaf4a"
color12 = "#659fff"
color13 = "#d773e6"
color14 = "#90d1ff"
color15 = "#26f9b4"
border = "#1a1a1f"
comment = "#6c7086"
