# Background and foreground colors
background = #060217
foreground = #63E3B5

# Standard colors
palette = 0=#060217
palette = 1=#d45146
palette = 2=#dd6b2f
palette = 3=#ff954b
palette = 4=#447edf
palette = 5=#aa57b2
palette = 6=#76b4ff
palette = 7=#63E3B5

# Bright colors
palette = 8=#68686e
palette = 9=#ff7161
palette = 10=#ff8d3e
palette = 11=#ffaf4a
palette = 12=#659fff
palette = 13=#d773e6
palette = 14=#90d1ff
palette = 15=#26f9b4
