$color = rgba(6, 2, 23, 1)
$inner_color = rgba(6, 2, 23, 0.66)
$outer_color = rgba(170, 87, 178, 1)
$font_color = rgba(99, 227, 181, 1)
$placeholder_color = rgba(99, 227, 181, 0.7)
$check_color = rgba(118, 180, 255, 1)
