background            #060217
foreground            #63E3B5

# black
color0  #060217
color8  #68686e

# red
color1  #d45146
color9  #ff7161

# green
color2  #dd6b2f
color10 #ff8d3e

# yellow
color3  #ff954b
color11 #ffaf4a

# blue
color4  #447edf
color12 #659fff

# magenta
color5  #aa57b2
color13 #d773e6

#cyan
color6  #76b4ff
color14 #90d1ff

#white
color7  #63E3B5
color15 #26f9b4


