accent = "#ae6685"
cursor = "#B4B3B3"
foreground = "#B4B3B3"
background = "#070707"
border = "#161616"
selection_foreground = "#070707"
selection_background = "#B4B3B3"
color0 = "#070707"
color1 = "#c7807a"
color2 = "#fcaf7f"
color3 = "#ffd6a7"
color4 = "#ae6685"
color5 = "#ec8b9d"
color6 = "#ffc76e"
color7 = "#B4B3B3"
color8 = "#5f5d57"
color9 = "#e98f89"
color10 = "#ffbe7f"
color11 = "#ffce93"
color12 = "#cd759c"
color13 = "#ff96af"
color14 = "#ffd865"
color15 = "#fff1f0"
comment = "#5f5d57"
